name = "ConeProj"
uuid = "57e5918e-c4e5-47a8-bf19-0d608e0bd369"
authors = ["Nic Fishman"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
